spring.datasource.url=jdbc:h2:mem:inventory-db
spring.h2.console.enabled=true
spring.cloud.config.discovery.enabled=false
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

aspring.datasource.url=jdbc:h2:mem:inventory-db
spring.data.rest.base-path=/api
